# Generated by Django 3.2.23 on 2024-02-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('name1', models.CharField(max_length=255)),
                ('phone1', models.CharField(max_length=15)),
                ('clinic1', models.CharField(max_length=255)),
                ('email1', models.EmailField(max_length=254)),
                ('specification1', models.CharField(max_length=50)),
                ('state1', models.CharField(max_length=50)),
                ('city1', models.CharField(max_length=50)),
            ],
        ),
    ]
