# Generated by Django 3.2.23 on 2024-02-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMAPP', '0002_newproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproduct',
            old_name='proname',
            new_name='productname',
        ),
    ]
