# Generated by Django 3.2.23 on 2024-02-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMAPP', '0003_rename_proname_newproduct_productname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newproduct',
            new_name='newprodect',
        ),
        migrations.RenameField(
            model_name='newprodect',
            old_name='productname',
            new_name='proname',
        ),
    ]
