# Generated by Django 3.2.23 on 2024-02-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMAPP', '0004_auto_20240203_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1', models.CharField(max_length=100)),
                ('contact1', models.CharField(max_length=100)),
                ('name1', models.CharField(max_length=100)),
                ('email1', models.CharField(max_length=100)),
                ('department1', models.CharField(max_length=100)),
                ('cc1', models.CharField(max_length=100)),
                ('tags1', models.CharField(max_length=100)),
                ('assignticket1', models.CharField(max_length=100)),
                ('priority1', models.CharField(max_length=100)),
                ('service1', models.CharField(max_length=100)),
                ('insertpredefined1', models.CharField(max_length=100)),
                ('insertknowledge1', models.CharField(max_length=100)),
                ('textarea1', models.CharField(max_length=100)),
                ('attachments1', models.FileField(upload_to='')),
            ],
        ),
    ]
