# Generated by Django 3.2.23 on 2024-02-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMAPP', '0005_tickets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tickets',
            new_name='ticket',
        ),
    ]
