# Generated by Django 3.2.23 on 2024-02-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMAPP', '0007_closed_doctor2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor1',
        ),
    ]
