# Generated by Django 3.2.23 on 2024-02-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMAPP', '0009_calllater_followup_insert_notintrested_rnr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Closed',
        ),
    ]
