# Generated by Django 3.2.23 on 2024-02-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMAPP', '0011_closed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Closed',
        ),
    ]
