# Generated by Django 3.2.23 on 2024-02-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMAPP', '0013_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('clinic_name', models.CharField(max_length=200)),
                ('phone1', models.CharField(blank=True, max_length=100, null=True)),
                ('phone2', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('specialisation', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('status1', models.CharField(max_length=100)),
                ('type_int', models.CharField(max_length=100)),
                ('priority_int', models.CharField(max_length=100)),
                ('datetime_int', models.DateField()),
                ('producttype_int', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('product_type_cl', models.CharField(max_length=200)),
                ('product_cl', models.CharField(max_length=200)),
                ('quantity_cl', models.IntegerField()),
                ('price_cl', models.IntegerField()),
                ('discount_cl', models.IntegerField()),
                ('balance_cl', models.IntegerField()),
                ('payment_type_cl', models.CharField(max_length=100)),
                ('offer_cl', models.CharField(max_length=200)),
                ('installing_date_cl', models.DateField()),
                ('installation_type_cl', models.CharField(max_length=100)),
                ('duration_from_cl', models.DateField()),
                ('duration_to_cl', models.DateField()),
                ('description_cl', models.TextField(max_length=1000)),
                ('datetime_folloup', models.DateTimeField()),
                ('description_folloup', models.TextField(max_length=1000)),
                ('datetime_notint', models.DateTimeField()),
                ('description_notint', models.TextField(max_length=1000)),
                ('datetime_rnr', models.DateTimeField()),
                ('datetime_clr', models.DateTimeField()),
                ('description_clr', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_int', models.CharField(max_length=100)),
                ('priority_int', models.CharField(max_length=100)),
                ('datetime_int', models.DateField()),
                ('producttype_int', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_folloup', models.DateTimeField()),
                ('description_folloup', models.TextField(max_length=1000)),
                ('datetime_rnr', models.DateTimeField()),
                ('description_rnr', models.TextField(max_length=1000)),
                ('datetime_clr', models.DateTimeField()),
                ('description_clr', models.TextField(max_length=1000)),
            ],
        ),
    ]
