# Generated by Django 3.2.23 on 2024-02-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMAPP', '0014_calldata_leads_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='newleads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=50)),
                ('Specialisation', models.CharField(max_length=50)),
                ('Assigned', models.CharField(max_length=50)),
                ('Tag', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('Emailaddress', models.CharField(max_length=50)),
                ('Website', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Zipcode', models.CharField(max_length=50)),
                ('Language', models.CharField(max_length=50)),
                ('Discription', models.CharField(max_length=50)),
                ('Priority', models.CharField(max_length=50)),
                ('Remark', models.CharField(max_length=50)),
            ],
        ),
    ]
