# Generated by Django 3.2.23 on 2024-02-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMAPP', '0015_newleads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newleads',
            new_name='newlead',
        ),
    ]
