# Generated by Django 3.2.23 on 2024-02-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMAPP', '0018_newlead'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newlead',
            new_name='newleads',
        ),
    ]
