# Generated by Django 3.2.24 on 2024-02-09 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMAPP', '0022_rename_username_logins_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
    ]
