# Generated by Django 3.2.24 on 2024-02-09 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMAPP', '0023_remove_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='LOGIN',
        ),
        migrations.DeleteModel(
            name='logins',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
