# Generated by Django 3.2.24 on 2024-02-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMAPP', '0025_logins_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='newstaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phoneno', models.IntegerField()),
                ('defaultlanguage', models.CharField(max_length=50)),
                ('emailsig', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
                ('hourlyrate', models.IntegerField()),
                ('facebook', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('skype', models.CharField(max_length=50)),
                ('defaultstate', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
