# Generated by Django 3.2.24 on 2024-02-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMAPP', '0026_newstaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstaff',
            name='firstname',
        ),
        migrations.AddField(
            model_name='newstaff',
            name='Firstname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
