# Generated by Django 3.2.24 on 2024-02-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMAPP', '0028_auto_20240212_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstaff',
            name='Lastname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
