# Generated by Django 3.2.24 on 2024-02-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMAPP', '0029_alter_newstaff_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstaff',
            name='Defaultlanguage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newstaff',
            name='Defaultstate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newstaff',
            name='Direction',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newstaff',
            name='Email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newstaff',
            name='Emailsig',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newstaff',
            name='Facebook',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newstaff',
            name='Linkedin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newstaff',
            name='Password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newstaff',
            name='Skype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
