# Generated by Django 3.2.24 on 2024-02-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMAPP', '0030_auto_20240212_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstaff',
            name='Hourlyrate',
        ),
    ]
