# Generated by Django 3.2.24 on 2024-02-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMAPP', '0031_remove_newstaff_hourlyrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Insert',
        ),
    ]
